version: '3.7'

services:
  deluge:
    image: linuxserver/deluge:latest
    container_name: deluge
    # network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
      - TZ=America/Sao_Paulo
      - DELUGE_WEB_PASSWORD=${DELUGE_WEB_PASSWORD}
    volumes:
      - ./services/deluge/config:/config
      - ./services/downloads/:/downloads
      - ./services/share/:/share
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - mynetwork
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    # network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
      - TZ=America/Sao_Paulo
      - API_KEY=${API_KEY_JACKET}
      - WEB_UI_USERNAME=${WEB_UI_USERNAME_JACKETT}
      - WEB_UI_PASSWORD=${WEB_UI_PASSWORD_JACKETT}
    volumes:
      - ./services/deluge/config:/config
      - ./services/jackett/config:/config
      - ./services/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - mynetwork
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    # network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
      - TZ=America/Sao_Paulo
    ports:
      - 8989:8989
    volumes:
      - ./services/sonarr/config:/config
      - ./services/series:/tv
      - ./services/downloads:/downloads
    restart: unless-stopped
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge